### ISSUE TITLE
generated pc identifier seems not stable.

### ISSUE THREAD

**Issue by bwlee** [open-license-manager/open-license-manager#14]
I found something alike in same computer, the signature/pc identifier not stable,  same license file, sometimes failed and reporting license corrupted.

**Comment by huoweijing0326** [comment]
Me too. VMware Workstation 14 + Windows 7 SP1 x64 + Qt5.7.1 with MinGW530_32, the example said "license signature didn't match with current license". But,  Windows 10 + Qt5.7.1 with MinGW530_32 doesn't.

**Comment by gemfield** [comment]
Some device uuid/info may changed after resume the virtual environment.

**Comment by gcontini** [comment]
Possible solution is to let the client change the identifier strategy with an environment variable, to find some uuid that don't change.

**Comment by gcontini** [comment]
If the mac address changes across reboots the only way is to use a disk based identifier. 
Recently i've found there was an array size that was wrong, so this bug should have been fixed by now. If it's still open please reopen the issue.
Here is how to change the default identifier strategy in case the mac address isn't stable in your environment: https://open-license-manager.github.io/open-license-manager/api/extend.html 
BR
Gabriele
