### ISSUE TITLE
Add obfuscation

### ISSUE THREAD

**Issue by lurumdare** [open-license-manager/open-license-manager#22]
Someone from the developers want to add to the project this https://github.com/fritzone/obfy ?

**Comment by gcontini** [comment]
Interesting link. Indeed obfuscation is necessary especially for an open source licensing library.

There is another intrinsic weakness to keep in mind. We need to use this library in java and python, the api need to be very simple, and that's until now the easiest point of attack. 

My current effort is on:
1) getting the tests to work, otherwise every modification risk to break other people's work.
2) rearrange the build in order to make it more robust and modular. I'll publish a document about that feel free to comment.
Thanks for your contributions until now.

**Comment by lurumdare** [comment]
@gcontini check https://github.com/lurumdare/open-license-manager/tree/obfy this branch if u interested. 

I think obfy only for C++.

**Comment by lurumdare** [comment]
The research showed that the use of this project (obfy) has little meaning in front of advanced technologies (virtualization(Themida,VMProtect) ). The weak point in virtualization is the use of functions similar to strcmp and external calls (Intermodular calls)

It is worth paying more attention to working with the network, so that it is more difficult for an attacker to emulate a server.

**Comment by emgstabilis** [comment]
Indeed, a better protection would be to have the client software connect
over the network to either a license server that you (software editor)
control, or that is protected with a reasonably difficult-to-crack hardware
usb token.

The certificate authority's public certificate would still need to be
installed on the client, which would be a weak point of the system.

**Comment by lurumdare** [comment]
@emgstabilis 
I believe that a hardware USB token is meaningless in this case. Better use obfuscation syscalls, for example. Well, bind this obfuscation to a secure server (to minimize MITM).
