### ISSUE TITLE
EVP_DigestVerifyFinal validation is failing always

### ISSUE THREAD

**Issue by senthilsam** [open-license-manager/open-license-manager#98]
For me EVP_DigestVerifyFinal validation return 0 even if i validate a fresh license. Please advise on this

**Comment by gcontini** [comment]
It's strange, maybe it's caused by some old version of the library still present on your pc. try to remove any globally installed lccgen version and checkout fresh. EG. check out [examples](https://github.com/open-license-manager/examples/tree/develop/submodule) in a clean subfolder.

Operating system and openssl version?
Are you issuing a license in windows and using it in Linux? (we don't have an test for interoperability, even if it should be possible to do this)

**Comment by gcontini** [comment]
inactive for very long time. and no extra info provided. Closing it
